/**
 * generated by Xtext 2.14.0
 */
package ru.spbstu.application.configurator.model.ui.contentassist;

import ru.spbstu.application.configurator.model.ui.contentassist.AbstractInfoProjectProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class InfoProjectProposalProvider extends AbstractInfoProjectProposalProvider {
}
