/**
 * generated by Xtext 2.14.0
 */
package ru.spbstu.application.configurator.model.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import ru.spbstu.application.configurator.model.ui.AbstractInfoProjectUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class InfoProjectUiModule extends AbstractInfoProjectUiModule {
  public InfoProjectUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
