/**
 * generated by Xtext 2.14.0
 */
package ru.spbstu.application.configurator.model.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import ru.spbstu.application.configurator.model.InfoProjectRuntimeModule;
import ru.spbstu.application.configurator.model.InfoProjectStandaloneSetup;
import ru.spbstu.application.configurator.model.ide.InfoProjectIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class InfoProjectIdeSetup extends InfoProjectStandaloneSetup {
  @Override
  public Injector createInjector() {
    InfoProjectRuntimeModule _infoProjectRuntimeModule = new InfoProjectRuntimeModule();
    InfoProjectIdeModule _infoProjectIdeModule = new InfoProjectIdeModule();
    return Guice.createInjector(Modules2.mixin(_infoProjectRuntimeModule, _infoProjectIdeModule));
  }
}
