/**
 * generated by Xtext 2.14.0
 */
package ru.spbstu.application.configurator.model.ide;

import ru.spbstu.application.configurator.model.ide.AbstractInfoProjectIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class InfoProjectIdeModule extends AbstractInfoProjectIdeModule {
}
