/*
 * generated by Xtext 2.14.0
 */
package ru.spbstu.application.configurator.model.ide


/**
 * Use this class to register ide components.
 */
class InfoProjectIdeModule extends AbstractInfoProjectIdeModule {
}
