/*
 * generated by Xtext 2.14.0
 */
package ru.spbstu.application.configurator.model.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import ru.spbstu.application.configurator.model.ui.internal.ModelActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class InfoProjectExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ModelActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ModelActivator activator = ModelActivator.getInstance();
		return activator != null ? activator.getInjector(ModelActivator.RU_SPBSTU_APPLICATION_CONFIGURATOR_MODEL_INFOPROJECT) : null;
	}

}
