/*
 * generated by Xtext 2.14.0
 */
package ru.spbstu.application.configurator.model


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class InfoProjectRuntimeModule extends AbstractInfoProjectRuntimeModule {
}
