/*
 * generated by Xtext 2.14.0
 */
package ru.spbstu.application.configurator.model


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class InfoProjectStandaloneSetup extends InfoProjectStandaloneSetupGenerated {

	def static void doSetup() {
		new InfoProjectStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
