/*
 * generated by Xtext 2.14.0
 */
package ru.spbstu.application.configurator.model.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import ru.spbstu.application.configurator.model.ide.contentassist.antlr.internal.InternalInfoProjectParser;
import ru.spbstu.application.configurator.model.services.InfoProjectGrammarAccess;

public class InfoProjectParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(InfoProjectGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, InfoProjectGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getPrefixAccess().getNameAlternatives_2_0(), "rule__Prefix__NameAlternatives_2_0");
			builder.put(grammarAccess.getUriAccess().getNameAlternatives_3_0(), "rule__Uri__NameAlternatives_3_0");
			builder.put(grammarAccess.getFeatureNameAccess().getNameAlternatives_2_0(), "rule__FeatureName__NameAlternatives_2_0");
			builder.put(grammarAccess.getCategoryAccess().getAlternatives(), "rule__Category__Alternatives");
			builder.put(grammarAccess.getCategoryAccess().getAlternatives_1(), "rule__Category__Alternatives_1");
			builder.put(grammarAccess.getMCSAccess().getNameAlternatives_2_0(), "rule__MCS__NameAlternatives_2_0");
			builder.put(grammarAccess.getValueAccess().getNameAlternatives_3_0(), "rule__Value__NameAlternatives_3_0");
			builder.put(grammarAccess.getPaddingSchemeAccess().getAlternatives(), "rule__PaddingScheme__Alternatives");
			builder.put(grammarAccess.getBootstrapAccess().getNameAlternatives_3_0(), "rule__Bootstrap__NameAlternatives_3_0");
			builder.put(grammarAccess.getSuperUserPasswordAccess().getNameAlternatives_3_0(), "rule__SuperUserPassword__NameAlternatives_3_0");
			builder.put(grammarAccess.getAdminPasswordAccess().getNameAlternatives_3_0(), "rule__AdminPassword__NameAlternatives_3_0");
			builder.put(grammarAccess.getParentSpaceRootXdbLibraryAccess().getNameAlternatives_3_0(), "rule__ParentSpaceRootXdbLibrary__NameAlternatives_3_0");
			builder.put(grammarAccess.getSubPathAccess().getNameAlternatives_3_0(), "rule__SubPath__NameAlternatives_3_0");
			builder.put(grammarAccess.getCloseHintDateQueryAccess().getNameAlternatives_3_0(), "rule__CloseHintDateQuery__NameAlternatives_3_0");
			builder.put(grammarAccess.getAiuThresholdAccess().getNameAlternatives_3_0(), "rule__AiuThreshold__NameAlternatives_3_0");
			builder.put(grammarAccess.getPKeyQueryAccess().getNameAlternatives_3_0(), "rule__PKeyQuery__NameAlternatives_3_0");
			builder.put(grammarAccess.getCiStoreAccess().getNameAlternatives_3_0(), "rule__CiStore__NameAlternatives_3_0");
			builder.put(grammarAccess.getLogStoreAccess().getNameAlternatives_3_0(), "rule__LogStore__NameAlternatives_3_0");
			builder.put(grammarAccess.getPdiConfigsAccess().getNameAlternatives_6_0(), "rule__PdiConfigs__NameAlternatives_6_0");
			builder.put(grammarAccess.getRenditionStoreAccess().getNameAlternatives_3_0(), "rule__RenditionStore__NameAlternatives_3_0");
			builder.put(grammarAccess.getPoliciesAccess().getNameAlternatives_4_0(), "rule__Policies__NameAlternatives_4_0");
			builder.put(grammarAccess.getSipStoreAccess().getNameAlternatives_3_0(), "rule__SipStore__NameAlternatives_3_0");
			builder.put(grammarAccess.getXdbLibraryParentAccess().getNameAlternatives_3_0(), "rule__XdbLibraryParent__NameAlternatives_3_0");
			builder.put(grammarAccess.getXdbModeAccess().getNameAlternatives_3_0(), "rule__XdbMode__NameAlternatives_3_0");
			builder.put(grammarAccess.getXdbStoreAccess().getNameAlternatives_3_0(), "rule__XdbStore__NameAlternatives_3_0");
			builder.put(grammarAccess.getXmlStoreAccess().getNameAlternatives_3_0(), "rule__XmlStore__NameAlternatives_3_0");
			builder.put(grammarAccess.getApplication_attrAccess().getNameAlternatives_3_0(), "rule__Application_attr__NameAlternatives_3_0");
			builder.put(grammarAccess.getTenant_attrAccess().getNameAlternatives_3_0(), "rule__Tenant_attr__NameAlternatives_3_0");
			builder.put(grammarAccess.getFileNameAccess().getNameAlternatives_3_0(), "rule__FileName__NameAlternatives_3_0");
			builder.put(grammarAccess.getStoreAccess().getNameAlternatives_3_0(), "rule__Store__NameAlternatives_3_0");
			builder.put(grammarAccess.getSuffixAccess().getNameAlternatives_3_0(), "rule__Suffix__NameAlternatives_3_0");
			builder.put(grammarAccess.getAip_idAccess().getNameAlternatives_3_0(), "rule__Aip_id__NameAlternatives_3_0");
			builder.put(grammarAccess.getIa_conf_datetimeAccess().getNameAlternatives_3_0(), "rule__Ia_conf_datetime__NameAlternatives_3_0");
			builder.put(grammarAccess.getIa_conf_typeAccess().getNameAlternatives_3_0(), "rule__Ia_conf_type__NameAlternatives_3_0");
			builder.put(grammarAccess.getHoldingsAccess().getNameAlternatives_2_0(), "rule__Holdings__NameAlternatives_2_0");
			builder.put(grammarAccess.getTypesAccess().getNameAlternatives_2_0(), "rule__Types__NameAlternatives_2_0");
			builder.put(grammarAccess.getCryptoEncodingAccess().getNameAlternatives_3_0(), "rule__CryptoEncoding__NameAlternatives_3_0");
			builder.put(grammarAccess.getCryptoEnabledAccess().getNameAlternatives_3_0(), "rule__CryptoEnabled__NameAlternatives_3_0");
			builder.put(grammarAccess.getCryptoObject_attrAccess().getNameAlternatives_3_0(), "rule__CryptoObject_attr__NameAlternatives_3_0");
			builder.put(grammarAccess.getSchemaAccess().getNameAlternatives_3_0(), "rule__Schema__NameAlternatives_3_0");
			builder.put(grammarAccess.getFileDeclarationAccess().getAlternatives_2_0(), "rule__FileDeclaration__Alternatives_2_0");
			builder.put(grammarAccess.getFileDeclarationAccess().getAlternatives_3_0(), "rule__FileDeclaration__Alternatives_3_0");
			builder.put(grammarAccess.getEnumOfArchiveTypeAccess().getAlternatives(), "rule__EnumOfArchiveType__Alternatives");
			builder.put(grammarAccess.getEnumOfTypesAccess().getAlternatives(), "rule__EnumOfTypes__Alternatives");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getVersionAccess().getGroup(), "rule__Version__Group__0");
			builder.put(grammarAccess.getNamespaceAccess().getGroup(), "rule__Namespace__Group__0");
			builder.put(grammarAccess.getPrefixAccess().getGroup(), "rule__Prefix__Group__0");
			builder.put(grammarAccess.getUriAccess().getGroup(), "rule__Uri__Group__0");
			builder.put(grammarAccess.getFeatureNameAccess().getGroup(), "rule__FeatureName__Group__0");
			builder.put(grammarAccess.getApplicationAccess().getGroup(), "rule__Application__Group__0");
			builder.put(grammarAccess.getTenantAccess().getGroup(), "rule__Tenant__Group__0");
			builder.put(grammarAccess.getHoldAccess().getGroup(), "rule__Hold__Group__0");
			builder.put(grammarAccess.getArchiveTypeAccess().getGroup(), "rule__ArchiveType__Group__0");
			builder.put(grammarAccess.getCategoryAccess().getGroup_0(), "rule__Category__Group_0__0");
			builder.put(grammarAccess.getDescriptionAccess().getGroup(), "rule__Description__Group__0");
			builder.put(grammarAccess.getDescriptionAccess().getGroup_4(), "rule__Description__Group_4__0");
			builder.put(grammarAccess.getMCSAccess().getGroup(), "rule__MCS__Group__0");
			builder.put(grammarAccess.getTypeAccess().getGroup(), "rule__Type__Group__0");
			builder.put(grammarAccess.getHoldTypeAccess().getGroup(), "rule__HoldType__Group__0");
			builder.put(grammarAccess.getTypeAttributeAccess().getGroup(), "rule__TypeAttribute__Group__0");
			builder.put(grammarAccess.getReceiveNodeAccess().getGroup(), "rule__ReceiveNode__Group__0");
			builder.put(grammarAccess.getRetentionPolicyAccess().getGroup(), "rule__RetentionPolicy__Group__0");
			builder.put(grammarAccess.getAgingPeriodAccess().getGroup(), "rule__AgingPeriod__Group__0");
			builder.put(grammarAccess.getUnitsAccess().getGroup(), "rule__Units__Group__0");
			builder.put(grammarAccess.getValueAccess().getGroup(), "rule__Value__Group__0");
			builder.put(grammarAccess.getAgingStrategyAccess().getGroup(), "rule__AgingStrategy__Group__0");
			builder.put(grammarAccess.getDispositionStrategyAccess().getGroup(), "rule__DispositionStrategy__Group__0");
			builder.put(grammarAccess.getSpace_attrAccess().getGroup(), "rule__Space_attr__Group__0");
			builder.put(grammarAccess.getCryptoObjectAccess().getGroup(), "rule__CryptoObject__Group__0");
			builder.put(grammarAccess.getConfigureAccess().getGroup(), "rule__Configure__Group__0");
			builder.put(grammarAccess.getPaddingSchemeAccess().getGroup_0(), "rule__PaddingScheme__Group_0__0");
			builder.put(grammarAccess.getPaddingSchemeAccess().getGroup_1(), "rule__PaddingScheme__Group_1__0");
			builder.put(grammarAccess.getSecurityProviderAccess().getGroup(), "rule__SecurityProvider__Group__0");
			builder.put(grammarAccess.getXdbFederationAccess().getGroup(), "rule__XdbFederation__Group__0");
			builder.put(grammarAccess.getBootstrapAccess().getGroup(), "rule__Bootstrap__Group__0");
			builder.put(grammarAccess.getSuperUserPasswordAccess().getGroup(), "rule__SuperUserPassword__Group__0");
			builder.put(grammarAccess.getXdbDatabaseAccess().getGroup(), "rule__XdbDatabase__Group__0");
			builder.put(grammarAccess.getDefaultAccess().getGroup(), "rule__Default__Group__0");
			builder.put(grammarAccess.getAdminPasswordAccess().getGroup(), "rule__AdminPassword__Group__0");
			builder.put(grammarAccess.getSpaceRootXdbLibraryAccess().getGroup(), "rule__SpaceRootXdbLibrary__Group__0");
			builder.put(grammarAccess.getXdbLibraryAccess().getGroup(), "rule__XdbLibrary__Group__0");
			builder.put(grammarAccess.getParentSpaceRootXdbLibraryAccess().getGroup(), "rule__ParentSpaceRootXdbLibrary__Group__0");
			builder.put(grammarAccess.getSubPathAccess().getGroup(), "rule__SubPath__Group__0");
			builder.put(grammarAccess.getXdbLibraryPolicyAccess().getGroup(), "rule__XdbLibraryPolicy__Group__0");
			builder.put(grammarAccess.getAipQuotaAccess().getGroup(), "rule__AipQuota__Group__0");
			builder.put(grammarAccess.getAiuQuotaAccess().getGroup(), "rule__AiuQuota__Group__0");
			builder.put(grammarAccess.getCloseHintDateQueryAccess().getGroup(), "rule__CloseHintDateQuery__Group__0");
			builder.put(grammarAccess.getCloseModeAccess().getGroup(), "rule__CloseMode__Group__0");
			builder.put(grammarAccess.getCloseModeAccess().getGroup_3(), "rule__CloseMode__Group_3__0");
			builder.put(grammarAccess.getClosePeriodAccess().getGroup(), "rule__ClosePeriod__Group__0");
			builder.put(grammarAccess.getAiuThresholdAccess().getGroup(), "rule__AiuThreshold__Group__0");
			builder.put(grammarAccess.getPKeyQueryAccess().getGroup(), "rule__PKeyQuery__Group__0");
			builder.put(grammarAccess.getHoldingAccess().getGroup(), "rule__Holding__Group__0");
			builder.put(grammarAccess.getCiStoreAccess().getGroup(), "rule__CiStore__Group__0");
			builder.put(grammarAccess.getDefaultRetentionClassAccess().getGroup(), "rule__DefaultRetentionClass__Group__0");
			builder.put(grammarAccess.getLogStoreAccess().getGroup(), "rule__LogStore__Group__0");
			builder.put(grammarAccess.getManagedItemStoreAccess().getGroup(), "rule__ManagedItemStore__Group__0");
			builder.put(grammarAccess.getPdiConfigsAccess().getGroup(), "rule__PdiConfigs__Group__0");
			builder.put(grammarAccess.getPriorityAccess().getGroup(), "rule__Priority__Group__0");
			builder.put(grammarAccess.getRenditionStoreAccess().getGroup(), "rule__RenditionStore__Group__0");
			builder.put(grammarAccess.getRetentionClassesAccess().getGroup(), "rule__RetentionClasses__Group__0");
			builder.put(grammarAccess.getPoliciesAccess().getGroup(), "rule__Policies__Group__0");
			builder.put(grammarAccess.getSipStoreAccess().getGroup(), "rule__SipStore__Group__0");
			builder.put(grammarAccess.getStagingStoreAccess().getGroup(), "rule__StagingStore__Group__0");
			builder.put(grammarAccess.getSubPrioritiesAccess().getGroup(), "rule__SubPriorities__Group__0");
			builder.put(grammarAccess.getDeadlineAccess().getGroup(), "rule__Deadline__Group__0");
			builder.put(grammarAccess.getXdbLibraryParentAccess().getGroup(), "rule__XdbLibraryParent__Group__0");
			builder.put(grammarAccess.getXdbModeAccess().getGroup(), "rule__XdbMode__Group__0");
			builder.put(grammarAccess.getXdbStoreAccess().getGroup(), "rule__XdbStore__Group__0");
			builder.put(grammarAccess.getXmlStoreAccess().getGroup(), "rule__XmlStore__Group__0");
			builder.put(grammarAccess.getAuditEventAccess().getGroup(), "rule__AuditEvent__Group__0");
			builder.put(grammarAccess.getApplication_attrAccess().getGroup(), "rule__Application_attr__Group__0");
			builder.put(grammarAccess.getTenant_attrAccess().getGroup(), "rule__Tenant_attr__Group__0");
			builder.put(grammarAccess.getDeliveryChannelAccess().getGroup(), "rule__DeliveryChannel__Group__0");
			builder.put(grammarAccess.getFileNameAccess().getGroup(), "rule__FileName__Group__0");
			builder.put(grammarAccess.getOverwriteAccess().getGroup(), "rule__Overwrite__Group__0");
			builder.put(grammarAccess.getStoreAccess().getGroup(), "rule__Store__Group__0");
			builder.put(grammarAccess.getSuffixAccess().getGroup(), "rule__Suffix__Group__0");
			builder.put(grammarAccess.getConfirmationAccess().getGroup(), "rule__Confirmation__Group__0");
			builder.put(grammarAccess.getDeliveryChannelParametersAccess().getGroup(), "rule__DeliveryChannelParameters__Group__0");
			builder.put(grammarAccess.getAip_idAccess().getGroup(), "rule__Aip_id__Group__0");
			builder.put(grammarAccess.getIa_conf_datetimeAccess().getGroup(), "rule__Ia_conf_datetime__Group__0");
			builder.put(grammarAccess.getIa_conf_typeAccess().getGroup(), "rule__Ia_conf_type__Group__0");
			builder.put(grammarAccess.getHoldingsAccess().getGroup(), "rule__Holdings__Group__0");
			builder.put(grammarAccess.getTypesAccess().getGroup(), "rule__Types__Group__0");
			builder.put(grammarAccess.getHoldingCryptoAccess().getGroup(), "rule__HoldingCrypto__Group__0");
			builder.put(grammarAccess.getCryptoEncodingAccess().getGroup(), "rule__CryptoEncoding__Group__0");
			builder.put(grammarAccess.getCiAccess().getGroup(), "rule__Ci__Group__0");
			builder.put(grammarAccess.getCryptoEnabledAccess().getGroup(), "rule__CryptoEnabled__Group__0");
			builder.put(grammarAccess.getCryptoObject_attrAccess().getGroup(), "rule__CryptoObject_attr__Group__0");
			builder.put(grammarAccess.getPdiAccess().getGroup(), "rule__Pdi__Group__0");
			builder.put(grammarAccess.getSipAccess().getGroup(), "rule__Sip__Group__0");
			builder.put(grammarAccess.getPdisAccess().getGroup(), "rule__Pdis__Group__0");
			builder.put(grammarAccess.getSchemaAccess().getGroup(), "rule__Schema__Group__0");
			builder.put(grammarAccess.getIncludeAccess().getGroup(), "rule__Include__Group__0");
			builder.put(grammarAccess.getFileDeclarationAccess().getGroup(), "rule__FileDeclaration__Group__0");
			builder.put(grammarAccess.getFileDeclarationAccess().getGroup_0(), "rule__FileDeclaration__Group_0__0");
			builder.put(grammarAccess.getFileDeclarationAccess().getGroup_1(), "rule__FileDeclaration__Group_1__0");
			builder.put(grammarAccess.getFileDeclarationAccess().getGroup_2(), "rule__FileDeclaration__Group_2__0");
			builder.put(grammarAccess.getFileDeclarationAccess().getGroup_3(), "rule__FileDeclaration__Group_3__0");
			builder.put(grammarAccess.getIngestNodeAccess().getGroup(), "rule__IngestNode__Group__0");
			builder.put(grammarAccess.getEnumCODAccess().getGroup(), "rule__EnumCOD__Group__0");
			builder.put(grammarAccess.getEnumMRAccess().getGroup(), "rule__EnumMR__Group__0");
			builder.put(grammarAccess.getLogLevelAccess().getGroup(), "rule__LogLevel__Group__0");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_0(), "rule__Model__ElementAssignment_0");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_1(), "rule__Model__ElementAssignment_1");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_2(), "rule__Model__ElementAssignment_2");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_3(), "rule__Model__ElementAssignment_3");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_4(), "rule__Model__ElementAssignment_4");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_5(), "rule__Model__ElementAssignment_5");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_6(), "rule__Model__ElementAssignment_6");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_7(), "rule__Model__ElementAssignment_7");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_8(), "rule__Model__ElementAssignment_8");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_9(), "rule__Model__ElementAssignment_9");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_10(), "rule__Model__ElementAssignment_10");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_11(), "rule__Model__ElementAssignment_11");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_12(), "rule__Model__ElementAssignment_12");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_13(), "rule__Model__ElementAssignment_13");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_14(), "rule__Model__ElementAssignment_14");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_15(), "rule__Model__ElementAssignment_15");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_16(), "rule__Model__ElementAssignment_16");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_17(), "rule__Model__ElementAssignment_17");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_18(), "rule__Model__ElementAssignment_18");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_19(), "rule__Model__ElementAssignment_19");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_20(), "rule__Model__ElementAssignment_20");
			builder.put(grammarAccess.getModelAccess().getElementAssignment_21(), "rule__Model__ElementAssignment_21");
			builder.put(grammarAccess.getVersionAccess().getNameAssignment_2(), "rule__Version__NameAssignment_2");
			builder.put(grammarAccess.getNamespaceAccess().getFeatureAssignment_1(), "rule__Namespace__FeatureAssignment_1");
			builder.put(grammarAccess.getNamespaceAccess().getFeatureAssignment_2(), "rule__Namespace__FeatureAssignment_2");
			builder.put(grammarAccess.getPrefixAccess().getNameAssignment_2(), "rule__Prefix__NameAssignment_2");
			builder.put(grammarAccess.getUriAccess().getNameAssignment_3(), "rule__Uri__NameAssignment_3");
			builder.put(grammarAccess.getFeatureNameAccess().getNameAssignment_2(), "rule__FeatureName__NameAssignment_2");
			builder.put(grammarAccess.getApplicationAccess().getFeatures1Assignment_2(), "rule__Application__Features1Assignment_2");
			builder.put(grammarAccess.getApplicationAccess().getFeaturesAssignment_3(), "rule__Application__FeaturesAssignment_3");
			builder.put(grammarAccess.getApplicationAccess().getFeatureAssignment_4(), "rule__Application__FeatureAssignment_4");
			builder.put(grammarAccess.getApplicationAccess().getFeatureAssignment_5(), "rule__Application__FeatureAssignment_5");
			builder.put(grammarAccess.getApplicationAccess().getFeatureAssignment_6(), "rule__Application__FeatureAssignment_6");
			builder.put(grammarAccess.getApplicationAccess().getFeatureAssignment_7(), "rule__Application__FeatureAssignment_7");
			builder.put(grammarAccess.getTenantAccess().getFeaturesAssignment_2(), "rule__Tenant__FeaturesAssignment_2");
			builder.put(grammarAccess.getHoldAccess().getFeatures1Assignment_1(), "rule__Hold__Features1Assignment_1");
			builder.put(grammarAccess.getHoldAccess().getFeaturesAssignment_2(), "rule__Hold__FeaturesAssignment_2");
			builder.put(grammarAccess.getArchiveTypeAccess().getValueAssignment_1(), "rule__ArchiveType__ValueAssignment_1");
			builder.put(grammarAccess.getCategoryAccess().getNameAssignment_0_3(), "rule__Category__NameAssignment_0_3");
			builder.put(grammarAccess.getDescriptionAccess().getNameAssignment_3(), "rule__Description__NameAssignment_3");
			builder.put(grammarAccess.getMCSAccess().getNameAssignment_2(), "rule__MCS__NameAssignment_2");
			builder.put(grammarAccess.getTypeAccess().getValueAssignment_3(), "rule__Type__ValueAssignment_3");
			builder.put(grammarAccess.getHoldTypeAccess().getFeaturesAssignment_2(), "rule__HoldType__FeaturesAssignment_2");
			builder.put(grammarAccess.getHoldTypeAccess().getFeaturesAssignment_3(), "rule__HoldType__FeaturesAssignment_3");
			builder.put(grammarAccess.getTypeAttributeAccess().getNameAssignment_1(), "rule__TypeAttribute__NameAssignment_1");
			builder.put(grammarAccess.getReceiveNodeAccess().getFeaturesAssignment_2(), "rule__ReceiveNode__FeaturesAssignment_2");
			builder.put(grammarAccess.getRetentionPolicyAccess().getFeaturesAssignment_2(), "rule__RetentionPolicy__FeaturesAssignment_2");
			builder.put(grammarAccess.getRetentionPolicyAccess().getFeaturesAssignment_3(), "rule__RetentionPolicy__FeaturesAssignment_3");
			builder.put(grammarAccess.getRetentionPolicyAccess().getFeaturesAssignment_4(), "rule__RetentionPolicy__FeaturesAssignment_4");
			builder.put(grammarAccess.getAgingPeriodAccess().getFeaturesAssignment_1(), "rule__AgingPeriod__FeaturesAssignment_1");
			builder.put(grammarAccess.getAgingPeriodAccess().getFeaturesAssignment_2(), "rule__AgingPeriod__FeaturesAssignment_2");
			builder.put(grammarAccess.getUnitsAccess().getNameAssignment_2(), "rule__Units__NameAssignment_2");
			builder.put(grammarAccess.getValueAccess().getNameAssignment_3(), "rule__Value__NameAssignment_3");
			builder.put(grammarAccess.getAgingStrategyAccess().getFeaturesAssignment_1(), "rule__AgingStrategy__FeaturesAssignment_1");
			builder.put(grammarAccess.getAgingStrategyAccess().getFeaturesAssignment_2(), "rule__AgingStrategy__FeaturesAssignment_2");
			builder.put(grammarAccess.getDispositionStrategyAccess().getFeaturesAssignment_2(), "rule__DispositionStrategy__FeaturesAssignment_2");
			builder.put(grammarAccess.getSpace_attrAccess().getFeaturesAssignment_2(), "rule__Space_attr__FeaturesAssignment_2");
			builder.put(grammarAccess.getCryptoObjectAccess().getFeaturesAssignment_1(), "rule__CryptoObject__FeaturesAssignment_1");
			builder.put(grammarAccess.getCryptoObjectAccess().getFeaturesAssignment_2(), "rule__CryptoObject__FeaturesAssignment_2");
			builder.put(grammarAccess.getCryptoObjectAccess().getFeaturesAssignment_3(), "rule__CryptoObject__FeaturesAssignment_3");
			builder.put(grammarAccess.getCryptoObjectAccess().getFeaturesAssignment_4(), "rule__CryptoObject__FeaturesAssignment_4");
			builder.put(grammarAccess.getConfigureAccess().getNameAssignment_2(), "rule__Configure__NameAssignment_2");
			builder.put(grammarAccess.getPaddingSchemeAccess().getNameAssignment_0_3(), "rule__PaddingScheme__NameAssignment_0_3");
			builder.put(grammarAccess.getSecurityProviderAccess().getNameAssignment_2(), "rule__SecurityProvider__NameAssignment_2");
			builder.put(grammarAccess.getXdbFederationAccess().getFeatureAssignment_1(), "rule__XdbFederation__FeatureAssignment_1");
			builder.put(grammarAccess.getXdbFederationAccess().getFeatureAssignment_2(), "rule__XdbFederation__FeatureAssignment_2");
			builder.put(grammarAccess.getXdbFederationAccess().getFeatureAssignment_3(), "rule__XdbFederation__FeatureAssignment_3");
			builder.put(grammarAccess.getXdbFederationAccess().getFeatureAssignment_4(), "rule__XdbFederation__FeatureAssignment_4");
			builder.put(grammarAccess.getXdbFederationAccess().getFeatureAssignment_5(), "rule__XdbFederation__FeatureAssignment_5");
			builder.put(grammarAccess.getBootstrapAccess().getNameAssignment_3(), "rule__Bootstrap__NameAssignment_3");
			builder.put(grammarAccess.getSuperUserPasswordAccess().getNameAssignment_3(), "rule__SuperUserPassword__NameAssignment_3");
			builder.put(grammarAccess.getXdbDatabaseAccess().getFeaturesAssignment_1(), "rule__XdbDatabase__FeaturesAssignment_1");
			builder.put(grammarAccess.getXdbDatabaseAccess().getFeaturesAssignment_2(), "rule__XdbDatabase__FeaturesAssignment_2");
			builder.put(grammarAccess.getXdbDatabaseAccess().getFeaturesAssignment_3(), "rule__XdbDatabase__FeaturesAssignment_3");
			builder.put(grammarAccess.getXdbDatabaseAccess().getFeaturesAssignment_4(), "rule__XdbDatabase__FeaturesAssignment_4");
			builder.put(grammarAccess.getDefaultAccess().getNameAssignment_2(), "rule__Default__NameAssignment_2");
			builder.put(grammarAccess.getAdminPasswordAccess().getNameAssignment_3(), "rule__AdminPassword__NameAssignment_3");
			builder.put(grammarAccess.getSpaceRootXdbLibraryAccess().getFeaturesAssignment_1(), "rule__SpaceRootXdbLibrary__FeaturesAssignment_1");
			builder.put(grammarAccess.getSpaceRootXdbLibraryAccess().getFeaturesAssignment_2(), "rule__SpaceRootXdbLibrary__FeaturesAssignment_2");
			builder.put(grammarAccess.getSpaceRootXdbLibraryAccess().getFeaturesAssignment_3(), "rule__SpaceRootXdbLibrary__FeaturesAssignment_3");
			builder.put(grammarAccess.getXdbLibraryAccess().getFeaturesAssignment_1(), "rule__XdbLibrary__FeaturesAssignment_1");
			builder.put(grammarAccess.getXdbLibraryAccess().getFeaturesAssignment_2(), "rule__XdbLibrary__FeaturesAssignment_2");
			builder.put(grammarAccess.getXdbLibraryAccess().getFeaturesAssignment_3(), "rule__XdbLibrary__FeaturesAssignment_3");
			builder.put(grammarAccess.getParentSpaceRootXdbLibraryAccess().getNameAssignment_3(), "rule__ParentSpaceRootXdbLibrary__NameAssignment_3");
			builder.put(grammarAccess.getSubPathAccess().getNameAssignment_3(), "rule__SubPath__NameAssignment_3");
			builder.put(grammarAccess.getXdbLibraryPolicyAccess().getFeaturesAssignment_1(), "rule__XdbLibraryPolicy__FeaturesAssignment_1");
			builder.put(grammarAccess.getXdbLibraryPolicyAccess().getFeaturesAssignment_2(), "rule__XdbLibraryPolicy__FeaturesAssignment_2");
			builder.put(grammarAccess.getXdbLibraryPolicyAccess().getFeaturesAssignment_3(), "rule__XdbLibraryPolicy__FeaturesAssignment_3");
			builder.put(grammarAccess.getXdbLibraryPolicyAccess().getFeaturesAssignment_4(), "rule__XdbLibraryPolicy__FeaturesAssignment_4");
			builder.put(grammarAccess.getXdbLibraryPolicyAccess().getFeaturesAssignment_5(), "rule__XdbLibraryPolicy__FeaturesAssignment_5");
			builder.put(grammarAccess.getXdbLibraryPolicyAccess().getFeaturesAssignment_6(), "rule__XdbLibraryPolicy__FeaturesAssignment_6");
			builder.put(grammarAccess.getXdbLibraryPolicyAccess().getFeaturesAssignment_7(), "rule__XdbLibraryPolicy__FeaturesAssignment_7");
			builder.put(grammarAccess.getXdbLibraryPolicyAccess().getFeaturesAssignment_8(), "rule__XdbLibraryPolicy__FeaturesAssignment_8");
			builder.put(grammarAccess.getAipQuotaAccess().getNameAssignment_2(), "rule__AipQuota__NameAssignment_2");
			builder.put(grammarAccess.getAiuQuotaAccess().getNameAssignment_2(), "rule__AiuQuota__NameAssignment_2");
			builder.put(grammarAccess.getCloseHintDateQueryAccess().getNameAssignment_3(), "rule__CloseHintDateQuery__NameAssignment_3");
			builder.put(grammarAccess.getCloseModeAccess().getNameAssignment_2(), "rule__CloseMode__NameAssignment_2");
			builder.put(grammarAccess.getClosePeriodAccess().getNameAssignment_2(), "rule__ClosePeriod__NameAssignment_2");
			builder.put(grammarAccess.getAiuThresholdAccess().getNameAssignment_3(), "rule__AiuThreshold__NameAssignment_3");
			builder.put(grammarAccess.getPKeyQueryAccess().getNameAssignment_3(), "rule__PKeyQuery__NameAssignment_3");
			builder.put(grammarAccess.getHoldingAccess().getFeaturesAssignment_1(), "rule__Holding__FeaturesAssignment_1");
			builder.put(grammarAccess.getHoldingAccess().getFeaturesAssignment_2(), "rule__Holding__FeaturesAssignment_2");
			builder.put(grammarAccess.getHoldingAccess().getFeaturesAssignment_3(), "rule__Holding__FeaturesAssignment_3");
			builder.put(grammarAccess.getHoldingAccess().getFeaturesAssignment_4(), "rule__Holding__FeaturesAssignment_4");
			builder.put(grammarAccess.getHoldingAccess().getFeaturesAssignment_5(), "rule__Holding__FeaturesAssignment_5");
			builder.put(grammarAccess.getHoldingAccess().getFeaturesAssignment_6(), "rule__Holding__FeaturesAssignment_6");
			builder.put(grammarAccess.getHoldingAccess().getFeaturesAssignment_7(), "rule__Holding__FeaturesAssignment_7");
			builder.put(grammarAccess.getHoldingAccess().getFeaturesAssignment_8(), "rule__Holding__FeaturesAssignment_8");
			builder.put(grammarAccess.getHoldingAccess().getFeaturesAssignment_9(), "rule__Holding__FeaturesAssignment_9");
			builder.put(grammarAccess.getHoldingAccess().getFeaturesAssignment_10(), "rule__Holding__FeaturesAssignment_10");
			builder.put(grammarAccess.getHoldingAccess().getFeaturesAssignment_11(), "rule__Holding__FeaturesAssignment_11");
			builder.put(grammarAccess.getHoldingAccess().getFeaturesAssignment_12(), "rule__Holding__FeaturesAssignment_12");
			builder.put(grammarAccess.getHoldingAccess().getFeaturesAssignment_13(), "rule__Holding__FeaturesAssignment_13");
			builder.put(grammarAccess.getHoldingAccess().getFeaturesAssignment_14(), "rule__Holding__FeaturesAssignment_14");
			builder.put(grammarAccess.getHoldingAccess().getFeaturesAssignment_15(), "rule__Holding__FeaturesAssignment_15");
			builder.put(grammarAccess.getHoldingAccess().getFeaturesAssignment_16(), "rule__Holding__FeaturesAssignment_16");
			builder.put(grammarAccess.getHoldingAccess().getFeaturesAssignment_17(), "rule__Holding__FeaturesAssignment_17");
			builder.put(grammarAccess.getHoldingAccess().getFeaturesAssignment_18(), "rule__Holding__FeaturesAssignment_18");
			builder.put(grammarAccess.getCiStoreAccess().getNameAssignment_3(), "rule__CiStore__NameAssignment_3");
			builder.put(grammarAccess.getDefaultRetentionClassAccess().getNameAssignment_2(), "rule__DefaultRetentionClass__NameAssignment_2");
			builder.put(grammarAccess.getLogStoreAccess().getNameAssignment_3(), "rule__LogStore__NameAssignment_3");
			builder.put(grammarAccess.getManagedItemStoreAccess().getNameAssignment_2(), "rule__ManagedItemStore__NameAssignment_2");
			builder.put(grammarAccess.getPdiConfigsAccess().getNameAssignment_6(), "rule__PdiConfigs__NameAssignment_6");
			builder.put(grammarAccess.getPriorityAccess().getNameAssignment_2(), "rule__Priority__NameAssignment_2");
			builder.put(grammarAccess.getRenditionStoreAccess().getNameAssignment_3(), "rule__RenditionStore__NameAssignment_3");
			builder.put(grammarAccess.getRetentionClassesAccess().getFeaturesAssignment_3(), "rule__RetentionClasses__FeaturesAssignment_3");
			builder.put(grammarAccess.getRetentionClassesAccess().getFeatureAssignment_4(), "rule__RetentionClasses__FeatureAssignment_4");
			builder.put(grammarAccess.getPoliciesAccess().getNameAssignment_4(), "rule__Policies__NameAssignment_4");
			builder.put(grammarAccess.getSipStoreAccess().getNameAssignment_3(), "rule__SipStore__NameAssignment_3");
			builder.put(grammarAccess.getStagingStoreAccess().getNameAssignment_2(), "rule__StagingStore__NameAssignment_2");
			builder.put(grammarAccess.getSubPrioritiesAccess().getFeaturesAssignment_2(), "rule__SubPriorities__FeaturesAssignment_2");
			builder.put(grammarAccess.getDeadlineAccess().getFeaturesAssignment_1(), "rule__Deadline__FeaturesAssignment_1");
			builder.put(grammarAccess.getXdbLibraryParentAccess().getNameAssignment_3(), "rule__XdbLibraryParent__NameAssignment_3");
			builder.put(grammarAccess.getXdbModeAccess().getNameAssignment_3(), "rule__XdbMode__NameAssignment_3");
			builder.put(grammarAccess.getXdbStoreAccess().getNameAssignment_3(), "rule__XdbStore__NameAssignment_3");
			builder.put(grammarAccess.getXmlStoreAccess().getNameAssignment_3(), "rule__XmlStore__NameAssignment_3");
			builder.put(grammarAccess.getAuditEventAccess().getFeatureAssignment_1(), "rule__AuditEvent__FeatureAssignment_1");
			builder.put(grammarAccess.getAuditEventAccess().getFeatureAssignment_2(), "rule__AuditEvent__FeatureAssignment_2");
			builder.put(grammarAccess.getAuditEventAccess().getFeatureAssignment_3(), "rule__AuditEvent__FeatureAssignment_3");
			builder.put(grammarAccess.getAuditEventAccess().getFeatureAssignment_4(), "rule__AuditEvent__FeatureAssignment_4");
			builder.put(grammarAccess.getApplication_attrAccess().getNameAssignment_3(), "rule__Application_attr__NameAssignment_3");
			builder.put(grammarAccess.getTenant_attrAccess().getNameAssignment_3(), "rule__Tenant_attr__NameAssignment_3");
			builder.put(grammarAccess.getDeliveryChannelAccess().getFeatureAssignment_1(), "rule__DeliveryChannel__FeatureAssignment_1");
			builder.put(grammarAccess.getDeliveryChannelAccess().getFeatureAssignment_2(), "rule__DeliveryChannel__FeatureAssignment_2");
			builder.put(grammarAccess.getDeliveryChannelAccess().getFeatureAssignment_3(), "rule__DeliveryChannel__FeatureAssignment_3");
			builder.put(grammarAccess.getDeliveryChannelAccess().getFeatureAssignment_4(), "rule__DeliveryChannel__FeatureAssignment_4");
			builder.put(grammarAccess.getDeliveryChannelAccess().getFeatureAssignment_5(), "rule__DeliveryChannel__FeatureAssignment_5");
			builder.put(grammarAccess.getDeliveryChannelAccess().getFeatureAssignment_6(), "rule__DeliveryChannel__FeatureAssignment_6");
			builder.put(grammarAccess.getDeliveryChannelAccess().getFeatureAssignment_7(), "rule__DeliveryChannel__FeatureAssignment_7");
			builder.put(grammarAccess.getFileNameAccess().getNameAssignment_3(), "rule__FileName__NameAssignment_3");
			builder.put(grammarAccess.getOverwriteAccess().getNameAssignment_2(), "rule__Overwrite__NameAssignment_2");
			builder.put(grammarAccess.getStoreAccess().getNameAssignment_3(), "rule__Store__NameAssignment_3");
			builder.put(grammarAccess.getSuffixAccess().getNameAssignment_3(), "rule__Suffix__NameAssignment_3");
			builder.put(grammarAccess.getConfirmationAccess().getFeatureAssignment_1(), "rule__Confirmation__FeatureAssignment_1");
			builder.put(grammarAccess.getConfirmationAccess().getFeatureAssignment_2(), "rule__Confirmation__FeatureAssignment_2");
			builder.put(grammarAccess.getConfirmationAccess().getFeatureAssignment_3(), "rule__Confirmation__FeatureAssignment_3");
			builder.put(grammarAccess.getConfirmationAccess().getFeatureAssignment_4(), "rule__Confirmation__FeatureAssignment_4");
			builder.put(grammarAccess.getDeliveryChannelParametersAccess().getFeatureAssignment_1(), "rule__DeliveryChannelParameters__FeatureAssignment_1");
			builder.put(grammarAccess.getDeliveryChannelParametersAccess().getFeatureAssignment_2(), "rule__DeliveryChannelParameters__FeatureAssignment_2");
			builder.put(grammarAccess.getDeliveryChannelParametersAccess().getFeatureAssignment_3(), "rule__DeliveryChannelParameters__FeatureAssignment_3");
			builder.put(grammarAccess.getAip_idAccess().getNameAssignment_3(), "rule__Aip_id__NameAssignment_3");
			builder.put(grammarAccess.getIa_conf_datetimeAccess().getNameAssignment_3(), "rule__Ia_conf_datetime__NameAssignment_3");
			builder.put(grammarAccess.getIa_conf_typeAccess().getNameAssignment_3(), "rule__Ia_conf_type__NameAssignment_3");
			builder.put(grammarAccess.getHoldingsAccess().getNameAssignment_2(), "rule__Holdings__NameAssignment_2");
			builder.put(grammarAccess.getTypesAccess().getNameAssignment_2(), "rule__Types__NameAssignment_2");
			builder.put(grammarAccess.getHoldingCryptoAccess().getFeatureAssignment_1(), "rule__HoldingCrypto__FeatureAssignment_1");
			builder.put(grammarAccess.getHoldingCryptoAccess().getFeatureAssignment_2(), "rule__HoldingCrypto__FeatureAssignment_2");
			builder.put(grammarAccess.getHoldingCryptoAccess().getFeatureAssignment_3(), "rule__HoldingCrypto__FeatureAssignment_3");
			builder.put(grammarAccess.getHoldingCryptoAccess().getFeatureAssignment_4(), "rule__HoldingCrypto__FeatureAssignment_4");
			builder.put(grammarAccess.getHoldingCryptoAccess().getFeatureAssignment_5(), "rule__HoldingCrypto__FeatureAssignment_5");
			builder.put(grammarAccess.getHoldingCryptoAccess().getFeatureAssignment_6(), "rule__HoldingCrypto__FeatureAssignment_6");
			builder.put(grammarAccess.getCryptoEncodingAccess().getNameAssignment_3(), "rule__CryptoEncoding__NameAssignment_3");
			builder.put(grammarAccess.getCiAccess().getFeatureAssignment_1(), "rule__Ci__FeatureAssignment_1");
			builder.put(grammarAccess.getCiAccess().getFeatureAssignment_2(), "rule__Ci__FeatureAssignment_2");
			builder.put(grammarAccess.getCryptoEnabledAccess().getNameAssignment_3(), "rule__CryptoEnabled__NameAssignment_3");
			builder.put(grammarAccess.getCryptoObject_attrAccess().getNameAssignment_3(), "rule__CryptoObject_attr__NameAssignment_3");
			builder.put(grammarAccess.getPdiAccess().getFeatureAssignment_1(), "rule__Pdi__FeatureAssignment_1");
			builder.put(grammarAccess.getPdiAccess().getFeatureAssignment_2(), "rule__Pdi__FeatureAssignment_2");
			builder.put(grammarAccess.getSipAccess().getFeatureAssignment_1(), "rule__Sip__FeatureAssignment_1");
			builder.put(grammarAccess.getSipAccess().getFeatureAssignment_2(), "rule__Sip__FeatureAssignment_2");
			builder.put(grammarAccess.getPdisAccess().getFeatureAssignment_1(), "rule__Pdis__FeatureAssignment_1");
			builder.put(grammarAccess.getSchemaAccess().getNameAssignment_3(), "rule__Schema__NameAssignment_3");
			builder.put(grammarAccess.getIncludeAccess().getFilesAssignment_3(), "rule__Include__FilesAssignment_3");
			builder.put(grammarAccess.getIngestNodeAccess().getFeaturesAssignment_2(), "rule__IngestNode__FeaturesAssignment_2");
			builder.put(grammarAccess.getIngestNodeAccess().getFeaturesAssignment_3(), "rule__IngestNode__FeaturesAssignment_3");
			builder.put(grammarAccess.getIngestNodeAccess().getFeaturesAssignment_4(), "rule__IngestNode__FeaturesAssignment_4");
			builder.put(grammarAccess.getIngestNodeAccess().getFeaturesAssignment_5(), "rule__IngestNode__FeaturesAssignment_5");
			builder.put(grammarAccess.getEnumCODAccess().getNameAssignment_2(), "rule__EnumCOD__NameAssignment_2");
			builder.put(grammarAccess.getEnumMRAccess().getNameAssignment_2(), "rule__EnumMR__NameAssignment_2");
			builder.put(grammarAccess.getLogLevelAccess().getNameAssignment_2(), "rule__LogLevel__NameAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private InfoProjectGrammarAccess grammarAccess;

	@Override
	protected InternalInfoProjectParser createParser() {
		InternalInfoProjectParser result = new InternalInfoProjectParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public InfoProjectGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(InfoProjectGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
