/**
 * generated by Xtext 2.14.0
 */
package ru.spbstu.application.configurator.model;

import ru.spbstu.application.configurator.model.InfoProjectStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class InfoProjectStandaloneSetup extends InfoProjectStandaloneSetupGenerated {
  public static void doSetup() {
    new InfoProjectStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
