/**
 * generated by Xtext 2.14.0
 */
package ru.spbstu.application.configurator.model;

import ru.spbstu.application.configurator.model.AbstractInfoProjectRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class InfoProjectRuntimeModule extends AbstractInfoProjectRuntimeModule {
}
